# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: cdk-synth

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash
    working-directory: cdk/

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './cdk/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install -g aws-cdk
    - run: cdk synth eks-multi-arch-stack
    - run: cdk synth eks-multi-arch-stack-eksblueprint
    - run: cdk synth multi-arch-pipeline-stack
